2026-06-27T15:58:48.5487957Z ##[group]Run chmod +x gradlew
chmod +x gradlew
shell: /usr/bin/bash -e {0}
env:
  JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.19-10/x64
  JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.19-10/x64
chmod: cannot access 'gradlew': No such file or directory
Process completed with exit code 1.